[phases.setup]
nixPkgs = ["curl", "bash", "jq", "coreutils", "wget", "unzip", "gzip", "nodejs", "corepack"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install",
  "curl -sL https://install.apibara.com | bash",
  "find /root -name 'apibara' -type f 2>/dev/null || echo 'apibara not found'",
  "ls -la /root/.local/share/apibara/ || echo 'directory not found'"
]

[variables]
PATH = "$HOME/.local/bin:$PATH"

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm run start" 