[phases.setup]
nixPkgs = ["curl", "bash", "jq"]

[phases.install]
cmds = ["curl -sL https://install.apibara.com | bash"]

[variables]
PATH = "$HOME/.local/bin:$PATH"

[phases.build]
cmds = [
  "source /root/.bashrc && apibara prepare",
  "source /root/.bashrc && apibara build"
]

[start]
cmd = "source /root/.bashrc && apibara start" 