[phases.setup]
nixPkgs = ["curl", "bash", "jq", "coreutils", "wget", "unzip", "gzip"]

[phases.install]
cmds = ["curl -sL https://install.apibara.com | bash"]

[variables]
PATH = "$HOME/.local/bin:$PATH"

[phases.build]
cmds = [
  "export PATH=\"$HOME/.local/bin:$PATH\" && apibara prepare",
  "export PATH=\"$HOME/.local/bin:$PATH\" && apibara build"
]

[start]
cmd = "export PATH=\"$HOME/.local/bin:$PATH\" && apibara start" 